version: '3.7'

services:
  nginx:
    container_name: jcorry-dev_nginx-prod
    image: nginx:1.23.3
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
    restart: on-failure
    volumes:
      - ./nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs/bare.pem:/etc/nginx/ssl/bare.pem
      - ./nginx/certs/bare.key.pem:/etc/nginx/ssl/bare.key.pem
  website:
    build:
      context: ./website
      dockerfile: Dockerfile.prod
    container_name: jcorry-dev_website-prod
    expose:
      - 3000
      - 3001
    restart: on-failure
