version: '3.7'

services:
  nginx:
    container_name: jcorry-dev_nginx
    depends_on:
      local:
        condition: service_healthy
    image: nginx:1.23.3
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs/bare.pem:/etc/nginx/ssl/bare.pem
      - ./nginx/certs/bare.key.pem:/etc/nginx/ssl/bare.key.pem
  local:
    build: ./website
    container_name: jcorry-dev_local
    environment:
      - JCORRY_DEV_DOCUMENT_TITLE=Joey Corry (Local)
      - JCORRY_DEV_IS_VIA_DOCKER=true
    expose:
      - 3000
      - 3001
    healthcheck:
      test: curl -f http://localhost:3000 || exit 1
      interval: 10s
      timeout: 10s
    volumes:
      - ./website/common:/home/website/common
      - ./website/globals.d.ts:/home/website/globals.d.ts
      - ./website/pages:/home/website/pages
      - ./website/renderer:/home/website/renderer
      - ./website/server:/home/website/server
