version: '3.7'

services:
  nginx:
    container_name: jcorry-dev_nginx-prod
    image: nginx:1.23.3
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
    restart: on-failure
    volumes:
      - ./nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs/bare.pem:/etc/nginx/ssl/bare.pem
      - ./nginx/certs/bare.key.pem:/etc/nginx/ssl/bare.key.pem
      - ./nginx/certs/wildcard.pem:/etc/nginx/ssl/wildcard.pem
      - ./nginx/certs/wildcard.key.pem:/etc/nginx/ssl/wildcard.key.pem
  live:
    build:
      context: ./website
      dockerfile: Dockerfile.prod
    container_name: jcorry-dev_live-prod
    expose:
      - 3000
    restart: on-failure
  staging:
    build: ./website
    container_name: jcorry-dev_staging-prod
    environment:
      - JCORRY_DEV_DOCUMENT_TITLE=Joey Corry (Staging)
      - JCORRY_DEV_SERVER_PORT=4000
      - JCORRY_DEV_VITE_PORT=4001
    expose:
      - 4000
      - 4001
    volumes:
      - ./website/common:/home/website/common
      - ./website/globals.d.ts:/home/website/globals.d.ts
      - ./website/pages:/home/website/pages
      - ./website/renderer:/home/website/renderer
      - ./website/server:/home/website/server
