version: '3.7'

services:
  caddy:
    container_name: jcorry-dev_caddy-prod
    depends_on:
      live:
        condition: service_healthy
    image: caddy:2.6.4
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
    restart: on-failure
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/certs/bare.pem:/etc/ssl/bare.pem
      - ./caddy/certs/bare.key.pem:/etc/ssl/bare.key.pem
  live:
    build:
      context: ./website
      dockerfile: Dockerfile.prod
    container_name: jcorry-dev_live-prod
    environment:
      - JCORRY_DEV_IS_VIA_DOCKER=true
    expose:
      - 3000
    healthcheck:
      test: curl -f http://localhost:3000 || exit 1
      interval: 10s
      timeout: 10s
    restart: on-failure
