services:
    web:
        build:
            context: ./
            target: development
        environment:
            - JCORRY_PORT=${JCORRY_PORT-3000}
        labels:
            dev.orbstack.domains: jcorry.local
        ports:
            - '0.0.0.0:${JCORRY_DOCKER_HOST_PORT-3000}:${JCORRY_PORT-3000}'
        volumes:
            - ./config:/home/jcorry.dev/config
            - ./src:/home/jcorry.dev/src
