FROM node:20.10.0

WORKDIR /home/website

COPY .eslintrc .eslintignore .gitignore .prettierrc .prettierignore globals.d.ts nodemon.json \
    package.json pnpm-lock.yaml tsconfig.eslint.json tsconfig.json vite.config.ts ./
COPY common/ ./common/
COPY pages/ ./pages/
COPY renderer/ ./renderer/
COPY server/ ./server/

RUN npm install -g pnpm@8.12.1
RUN pnpm install --frozen-lockfile

CMD pnpm run prod
