FROM node:18.13.0

WORKDIR /home/website
COPY .eslintrc .eslintignore .gitignore .prettierrc globals.d.ts nodemon.json package.json \
    tsconfig.eslint.json tsconfig.json vite.config.ts yarn.lock ./
COPY common/ ./common/
COPY pages/ ./pages/
COPY renderer/ ./renderer/
COPY server/ ./server/
RUN yarn --frozen-lockfile --non-interactive

CMD yarn prod
